### ISSUE TITLE
如何让它继续回复呢？

### ISSUE THREAD

**Issue by 0x783kb** [lvwzhen/teach-anything#2]
它回复的代码并不完整，我应该怎样让他继续回复不完整的代码

**Comment by lvwzhen** [comment]
暂时不支持继续对话，连续对话可以在 https://chat.openai.com/ 中体验

**Comment by claviering** [comment]
https://github.com/lvwzhen/teach-anything/blob/0d481f464af765707de275d68e152b798e73a298/pages/api/generate.ts#L29

可以修改`max_tokens` 参数的值到大一点
