### ISSUE TITLE
Error:Missing evn var from OpenAI

### ISSUE THREAD

**Issue by xgd561** [lvwzhen/teach-anything#3]
在页面点击“Get the answer”按钮后，有这个错误产生，一般是什么原因？
.env.example文件里面的OPENAI_API_KEY已经填入了，从OpenAI的个人账户里面产生的。

**Comment by lvwzhen** [comment]
.env.example 改成 .env

**Comment by icenote2023** [comment]
改了还是错误，这是为什么呢
