### ISSUE TITLE
能否加一个动态切换OPENAI_API_KEY

### ISSUE THREAD

**Issue by xyy002** [lvwzhen/teach-anything#4]
能否加一个动态切换OPENAI_API_KEY

**Comment by lvwzhen** [comment]
对于普通用户，填写key太过复杂。

程序员的话可以使用一键部署到Vercel中，谢谢支持。

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https://github.com/lvwzhen/teach-anything&env=OPENAI_API_KEY&project-name=teach-anything&repo-name=teach-anything)
