### ISSUE TITLE
Prompt Idea

### ISSUE THREAD

**Issue by brandco** [lvwzhen/teach-anything#6]
I like this app

I entered:

What is the early history of Brazil’s independence from Portugal?

The response for professional option is divided into two sections that don't make a lot of sense for the question. 

Try this prompt with your same api settings for openai completion endpoint:

{
Given the following questions write a 3000 token response in three paragraphs at a college level?

What is the early history of Brazil’s independence from Portugal?
}

It'd be cool if I could load my own prompt templates in a json object or something portable

Thanks for sharing this app

**Comment by lvwzhen** [comment]
You can try our new pro version: https://magickpen.com/  , with more Prompt options to choose from, the answer is more professional and reliable, thanks for your support.

![store-thum2](https://user-images.githubusercontent.com/2337506/221085495-5668f09e-5180-4a78-8f54-5238d690a0a1.png)
